import React from 'react';

export enum Tab {
  HOME = 'HOME',
  SEARCH = 'SEARCH',
  SCANNER = 'SCANNER',
  ORDERS = 'ORDERS',
  ORDER_HISTORY = 'ORDER_HISTORY',
  EARNINGS = 'EARNINGS',
  MENU = 'MENU',
  INVENTORY = 'INVENTORY',
  PROFILE = 'PROFILE',
  SUBSCRIPTION = 'SUBSCRIPTION',
  SETTINGS = 'SETTINGS',
  ADS_MARKETING = 'ADS_MARKETING',
  OFFERS = 'OFFERS',
  OUTLET = 'OUTLET',
  BUSINESS_SETUP = 'BUSINESS_SETUP',
  OUTLET_INFO = 'OUTLET_INFO',
  OWNER_INFO = 'OWNER_INFO',
  OPENING_HOURS = 'OPENING_HOURS',
  DIGITAL_MENU = 'DIGITAL_MENU',
  BANK_ACCOUNTS = 'BANK_ACCOUNTS',
  BUSINESS_DOCS = 'BUSINESS_DOCS',
  NOTIFICATIONS = 'NOTIFICATIONS',
  INTEGRATIONS = 'INTEGRATIONS',
  TABLES = 'TABLES',
  SALES_REPORT = 'SALES_REPORT',
  REFUNDS = 'REFUNDS',
  CUSTOMER_DATA = 'CUSTOMER_DATA',
  CREATE_OFFER = 'CREATE_OFFER',
  CREATE_ORDER = 'CREATE_ORDER',
  ANALYTICS = 'ANALYTICS',
  RELATIONSHIP_MANAGER = 'RELATIONSHIP_MANAGER',
  INVOICES = 'INVOICES',
  UPLOAD_BANNERS = 'UPLOAD_BANNERS',
  MANAGE_BILLING = 'MANAGE_BILLING',
  PARTNER_STORE = 'PARTNER_STORE',
  PARTNER_STORE_PRODUCT = 'PARTNER_STORE_PRODUCT',
  PARTNER_STORE_CHECKOUT = 'PARTNER_STORE_CHECKOUT',
  PARTNER_STORE_TRACKING = 'PARTNER_STORE_TRACKING',
  PIN_ON_MAP = 'PIN_ON_MAP',
  PAYOUT = 'PAYOUT',
  CUSTOMER_RATINGS = 'CUSTOMER_RATINGS',
  CUSTOMER_INFO = 'CUSTOMER_INFO',
  SUPPORT = 'SUPPORT',
  CREVINGS_STUDIO = 'CREVINGS_STUDIO',
  CREVINGS_LEGAL = 'CREVINGS_LEGAL',
  RECIPE = 'RECIPE',
  VEHICLE_DETAILS = 'VEHICLE_DETAILS',
  PROFILE_DETAILS = 'PROFILE_DETAILS',
  PERSONAL_DOCUMENTS = 'PERSONAL_DOCUMENTS'
}

export interface NavItem {
  id: Tab;
  label: string;
  icon: React.FC<any>;
}
